* 2015
** 10
*** 1018
…突発的な割り込みタスクはこなすのにも、覚えるのにも、元の物に戻るのにも頭を使う。もっと初めに機械的な定期的に起こすプロセスを作りそれに從うべき。その場合ルーチンは一日の早い段階で済ませてしまうべき。
…家を出る時など些細なことでも機械的に行えるチェックリストを作る。プログラムの二回以上行う処理を関数にする感覚で。

** 12
*** 1229
やりだすと時間がかかる上に、実際に片付いているのを継続するには現実の生活に沿った周りの物の配置が必要になるので3月のバイト・卒論ともに落ち着いたときに一気にやってしまおうという計画。また今からどうするかをじっくりと考えて思いついたらメモしておこうと思う。
<2016-03-31 Thu 23:39>追記：
結局バイトも3月半ばで終わったのに、一日片付けに時間を割いたのを除いて何もやれてない。やはりいつ何をやるかのリマインダーを絶対につけておく必要があると思う。

* 2016
** 01
*** 0115
(未知のものに対して)怖いと思う感覚がどういうものか、イメージできないのでそのようなことに対する達観した感覚・距離を取った対応がつかめない。
無理に刺激を得ようと無駄ながんばりをしないように、
毎日１０分でもいいので見るようにする。
*** 0127 
勉強など何にしても次にやるべきこと、やったら前に進めることが何か分からない状態がやる気がなくなる場合が多いと思う。仮にそれに対して興味がなくても、それができることで効率的に嬉しくなれるならば自分の中でやる気が出てくるはず。
*** 0131
		文章とは根本的に、何かを説明したときに、そうでないものを裏に想定して庵にそれの否定をすること、つまり説明の補集合の否定を取ることを意味する。そういった意味では”注意することが無難である”みたいな無難な表現は何も言っていないのに等しい。決まり文句を使うことは、その文句が使われる状況を汲まずに誤った意味で使ってしまう、または特に間違ってはいなくても何も言及していないということを意味する。なんにしても、使う言葉はうまく取捨選択する必要があるし、影響を受けるメディアは選ばなければいけないと思う。
** 02
*** 0205
午後の3時~9時に眠くなった時はどうすればいい?
なぜかちょっと幸せな感覚がある（酒のときの麻痺ってるのと同じ？）
*** <2016-02-06 土 09:22>
	こうやってメモを取る習慣はけっこう必要なきがする。特に毎回texの文法をブラウザで調べ直すのは、かなり馬鹿馬鹿しいと思ってたので技術メモはしっかりつけていきたい。
*** <2016-02-06 土 10:20>
	珈琲飲んでるし、明らかに悪影響が強いお酒ぐらいは控えるほうにしたほうがいいのかもしれない。どうしても飲みたければその次の日何もしなくても後悔しないような日の前日にでもどうぞ。
*** <2016-02-06 土 19:00>
	何かを書くとき（形に残すとき）は、どこかしらでつまずいてそこでずっと止まってしまうことが多い。逆にそこを超えてしまえば、大体の場合はスムーズに筆が（タイピングが）進むことが多い気がする。そういった意味では一日でも止まってしまう日が続いた場合には、あまり直接の関係がなくとも関連分野を手当たり次第調べて自分なりのイメージができるのを待ったほうが速いきがする。実際明後日までに仕上げるべきプレゼンが今あるが、今日はその辺りでどうしようか迷って、結局何回もemacsに戻ってほとんど変更を加えられなかった。一日猶予があるならこの方法を取ってみてもいいと思う。
*** <2016-02-07 日 11:39>
	ここ数日異常なまでに刺激に対してあまり深く考えずに行動してしまっている。一週間前ぐらいまでは仏教に関する本をいくつか読んでいたことも合って、自分の中でも比較的落ち着いて行動ができていた。きっかけは先週のセミナーで4時間ずっと説明していて疲労困憊になったこと、一昨日にjqueryで苦労してきれいなUIを構築できたことなどがあると思う。こういった状態には以前も何度かなっていたがこの状態にに気づくのはだいたい場の場合には生活の質が悪くなってからな気がする。座禅をよくするのは煩わしいことではあるが、日々の生活でこういった状態に陥らないためには必要なことなのかもしれない。
	個人的には刺激は生きていく上で必要なために発達してきたものだし、優先されて然るべきだと思う。ただ実際に生きていく中で、特にお金や計算機科学といった刺激が異常なまでに強い世界に生きていくならば、こういった強い刺激に溺れてしまう危険性は通常の生活を送るのに比べて高い。そういった意味でもこのように刺激に対して注意深い姿勢は必要なのかもしれない。ちなみにこの文章は本当に刺激に対して間隔なしに、思いつくままに書いてしまっている文章となっている。
*** <2016-02-07 日 17:02>
	もともとそんなにいい冷凍の唐揚げではないので、チャーハンと一緒に唐揚げを食べても残念な気分になるだけな気がする。白米やラーメンと一緒に食べるとそんなに悪くないのかもしれない。
*** <2016-02-09 火 09:47>
	1.Jazzを聴きながら
	2.ぶどうを口に含み
	3.堀口珈琲のブレンド１のフルーティなのを飲むと最高に幸せ
*** <2016-02-10 水 10:53>
	三条小川珈琲でブレンド頼んだ。フルーティーなやつベースでなかなかなおいしさだった。グテァマラやエチオピアなどベースでブレンド作ると、一般に出されるマンデリンに近い苦い珈琲じゃなくて爽やかなものが作れるのかも。あとこういうものの場合にはペーパードリップの長所が生かされてるのかもしれない。
	
*** <2016-02-10 水 23:34>
	眠い。メールで急にいろいろな処理を求められているので、かなりめんどくさい。こういうのやってると、社会に出てフォーマルに他人と交流を持つのもけっこうめんどくさいことなのかなと思ってしまう。

*** <2016-02-11 木 11:35>
	現在珈琲を飲み、ゲームBGMを聴き、やるべきことがたまっているという、かなり刺激が溢れて落ち着いて判断ができない状態になっている状態に気づいたらなっていた。気づいたのは英語論文のアブストラクトを落ち着いてみることができなかったため。食べる、飲む、音楽を聞くといったそれぞれの動作はたしかに刺激的で心地よいものではあるが、それらをする際にはリスクがかなり溢れていることをもう少し注意すべきかなと感じた。もちろん刺激を少なくしすぎてしまうと退屈で、却ってリバウンドのように刺激を求めてしまう結果にもなりかねないのでバランスは大事。
	
*** <2016-02-11 木 14:08>
	やっぱり自分の卒論を見直すのはかなりメンタル的にきつい。ふと思ったのはよく疲れて休憩をするけれども、その際に求められているのは休憩をする前の出来事から発生する刺激をある程度忘れることでそれらに起因する刺激を弱めることなのかなと思う。そういった意味では休憩にやりたいことを行うことは、それらの楽しい刺激で上書きしようとしているのだが、そうなるとその前にやっていたことをやりたくなくなってしまうのは至極当然な気がする。逆に突っ伏して短い時間寝ることはその点からいえばかなり合理的なのかもしれない。

*** <2016-02-11 木 19:07>
	割と何も考えずに西井の残していったテレビに食いついてしまった。これだけよいものをもらったら無意識に相手に引け目を感じてしまうことを、予めもう少し考えてから行動したほうがいいのかなと思う。

*** <2016-02-13 土 18:08>
昨日の焼き肉でいつの間にかお酒をある程度飲んでいたのにいつもと違うリズムで食事を取ったせいか、普通に珈琲を飲んでいただけなのに体調を崩してしまった。下手に経験則でバランスを元に考えるより、実際の体のサインをしっかりつかめるように、またそれを自身をもって理解できるようにできればなと思う。

*** <2016-02-14 日 20:37>
いつも頭がぼーっとしていて、何かに集中できていない状態になってはじめて自分が集中できていないことに気づいている。かといって日頃から刺激を少なめにしようとすると、なにか物足りなくなるので長くは続かない。なにかいいかんじに防ぐような規則を作れればいいのだろうけれども…

*** <2016-02-19 金 09:22>
	昨日バイトで軽い口論になったこともあってかあまり機嫌が良くない。それにしてもあまり調子よくないのになんでこんなに影響を受けているのかと考えると、fxの自動売買が思いの外全然思ったように動いてくれないところがある気がする。やっぱり自分でやるしかないのか…

*** <2016-02-28 日 10:59>
久しぶりの投稿。人と会った後は何かしらの原因で感情が大きく動かされることが多い。例えば親しい間柄の人と会って楽しい会話をすれば、その楽しい話を思い出してみたり、それと同じぐらい楽しいことを無意識にもとめてしまう。また仕事や勉強でうまくいかなかったり、人間関係でトラブってしまったりするとモヤモヤしてしまうことが多くなって、そのことが頭の中をぐるぐる回ってしまい他のことに集中できなかったりする。そういった意味では明らかに自分が感情を動かされるであろうタイミングは、ある程度予想できると思う。そういった人と会った日の寝る前に、予め座禅や深呼吸をするようにリマインダーを設定しておけば、効率よく気持ちを整理できるかも手数料しれない。

** 03
   
*** <2016-03-13 日 22:18>
漫画の中で見つけたセリフになるが、何かを努力し続けるためには努力しないこ

*** <2016-03-21 Mon 22:18>
Pokerにて
しばらく大きく勝っていたのに今日はかなり負けてしまった。
原因の一つは今まで慎重にいっていい手のときに一揆に強気に出られてこつこつ削り取られていた。今までうまくいってたのは明らかに間違った対応をしてきた相手が多くて、結果としてうまくつけいることができたからだったきがする。やはり相手の傾向をしっかり掴んで、自分のスタイルにはあまりこだわらずにその場・その人に対して最も有効な対応をするのがベストなのだと思う。

*** <2016-03-22 Tue 10:59>
堀口珈琲、丸山珈琲、nozy coffeeは見た感じ似たようなグレードの豆を扱っているよう。特に丸山珈琲はカフェインレスも売ってるのでもう少し詳しく見ていってもいいかも。nozyは少し高めな気がするけどおいしそうなシングルオリジンをいくつか揃えているようなので、一通り飲んだらここを調べるのもあり。

*** <2016-03-23 Wed 02:52>
ポーカーはテーブルによって、オーバーベットしがちなテーブルであるかとか、基本最後までオープンすることがないテーブルであるとかといった傾向が間違いなくある。最近わかってきたのはそのあたりの各プレーヤーの傾向を掴んで情報を利用していくことである程度山を貼ったりできる。ただそれらは普通プレイしてみてはじめてわかるものもあるが、テーブルをオブザーブしていけそうと判断してからプレイをし始めるのも一つの手段としてもっていてもいいきがする。あと今回いきなりむちゃくちゃなオール・インをされたのに場に2枚のスリーオブカインド・ハイカードJでのってしまってハイカードKに危うく5ユーロを一揆に失いかけた。オール・インに微妙な勝ち方で乗るのは躊躇したほうがいいと思う。

*** <2016-03-24 Thu 21:07>
自分にはグダグダする才能があると思っていたが、本当に目的がないとやることがループしてしまうし本当に何も進まないのでさすがに焦りも出てくる。なんだかんだで疲労を取るときと一緒で自分の頭をあまり使わないで適度に疲れる感じを出したほうが楽になるのかもしれない。実際archを導入していたときが一番いい感じだった気がする。バイトもタスクの難易度としてはちょうどいいが、やる対象が研究や興味とかけ離れてしまい、かつ時間を拘束されるのが辛いところといったところか。そういうわけでRNNでなんか作ろうと思っていろいろ調べてみるとpybrainがよさそう。ただipythonやらvirtualenvの環境構築が全然まだだったのでそこを今調べている。けっこう楽しい。

*** <2016-03-27 Sun 14:47>
椅子の上にバランスディスク載せただけでも、足を地面につけて普通に座ったら以外ときれいな姿勢になる。足元のヒーターもあつすぎないし、最初からこうすればよかった気もする。
あと意識するのは難しいが、この状態でお腹を引っ込めるとなかなかいい運動になる。このときはディスクの前側にのるとずり落ちてしまうため、自然とお腹を引っ込めて体制を安定させることができる。

*** <2016-03-31 Thu 23:32>
最近かなり怠惰な生活を送りまくってた自覚がある。ちょうど院試頃に一時期rescuetimeを使ってライフログをとるだけで、一日の勉強時間が8時間前後にまで伸びたことがあった。あのときはもちろん勉強しなければならないという状況だったことも理由の一つではあると思うが、それだけでもかなり自分の中で効果があり負担もでかかった。結果としていつのまにかやめてしまっていたが、自分の行動に自分が責任を持つという意味合いではすごく当たり前のことだと思う。それができないのならば、最初から遊ばなければいいと思う。とはいえ毎日自然にできる範囲でログをつける方法はまだ思いつかないが、何らかの方法で自分の行動を自分で管理する方法をそろそろ見つけないとまじでヤバイ。

** 04
*** <2016-04-01 Fri 02:27>
ログを久しぶりにとってみてわかったのは、結局のところ自分で後から考えれば後悔すると思っている行動を普段から思いつくままにやっていたとういうこと。記録しているのだと考えるだけでひとつ時間をおいてその行動をほんとうにしたいか、するべきかということを考えてからしているみたい。以前かなりうまくいったのは多分これが原因なのだろうと思う。

*** <2016-04-01 Fri 10:00>
今朝起きた後も自分の行動をログに取ることを把握していると、ベッドからなかなか起きられなかった。これは少し考えてから行動に移すことによって、次に何をやりたいかより何をやるべきかを考えてしまうためと思われる。こうなって初めて予定を組むことの意味がわかったきがする。予定を組まないといろいろな可能性が気になってしまい何もできなくなってしまうのだと思う。ある意味このような状態にならない限りは予定をいくら組んでも自分でその予定を組んでもその予定に従いたいと思えないのかもしれない。

*** <2016-04-01 Fri 10:07>
スケジューリングというか今日やっておきたいこと

**** TODO 論文読めるとこまで読む

**** TODO 昼夜ともに寮食食べて、橙食券の支払いも済ませる

**** PS4、vitaは2タイトルかつ2時間まで

**** chainer,tutorialページは理解する

*** <2016-04-05 Tue 10:37>
最近はゲーム、コーヒー、ps4などいろいろ楽しめるものができたきがする。ただどれもどうしたら最も楽しめるかを考えてばかりで、結局大量の刺激からは何も逃れられていない。かといって常にプログラミングをしているというのも悪くはないが、煮詰まったときになんかほしい。そういう意味では楽しくないときもあるが、本当の意味で落ち着ける仏教の本を読んだり座禅したりするのが刺激からの開放と言う意味では一番適当なのかもしれない。

*** <2016-04-09 土 09:34>
土日のどこかを使って毎週emacsやzshなどの普段から使ってる開発環境の整備をしたほうがいい気がする。明らかに現時点でzshは使いこなせてないし、かといってそれらをずっといじっているのにはさすがに限度がある。

*** <2016-04-11 月 20:43>
		今日マシューさんの英語を横で少し聞いていて思ったが、単語はちょくちょく聴き取れても文章として何を言っているかさっぱしわからなかった。もちろん本来の学習習慣が整ってからの話だが、そろそろ瞬間英作文みたいものを少しずつでも始めていかないとやばいのかなと思う。現時点でも英語の論文読んでて文章をフルで理解するのに何度も通し読みする必要があるし、もはや本来の勉強の時間効率としてもやってみてもいい段階になっている。
