#!/bin/bash

keyword=`zenity --entry --text=検索したいワードを入力してください --title='GoogleAPI'`
url_lists=(`wget -O - "http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=${keyword}"|jq '.responseData.results | .[].unescapedUrl'|nkf --url-input `)
for item in ${url_lists[@]}
do
    echo $item|xargs firefox -new-tab
done
